version: '3'
services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=appdb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - app-network
  app:
    build:
      context: node
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules

    tty: true
    container_name: app
    entrypoint: wait-for db:3306 -t 40 -- node index.js
    networks: 
      - app-network
    depends_on:
      - db
  nginx:
    build:
      context: ./nginx
    tty: true
    container_name: nginx
    networks:
      - app-network
    ports:
      - '8080:80'
    depends_on:
      - app

networks:
  app-network:
    driver: bridge
